language: ruby
services:
  - redis-server
rvm:
  - 2.2
  - 2.1
  - 2.0.0
branches:
  only:
    - master
notifications:
  email: false
gemfile:
  - gemfiles/sidekiq_2.gemfile
  - gemfiles/sidekiq_3.gemfile
  - gemfiles/sidekiq_4.gemfile
  - gemfiles/sidekiq_master.gemfile
